version: '3'

services:
  files:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - UNIT_TEST=${FLAG_UNIT_TEST}
    image: '${BUILD_IMAGE}'
    ports:
        - '3000:3000'   
