swagger: '2.0'
info:
  description: <Please edit your swagger document to add a description here.>
  version: 1.0.0
  title: project
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: project
    description: <Please edit your swagger document to add a description here.>
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
paths:
  /healthcheck:
    get:
      tags:
        - healthcheck
      summary: Check the health of the application
      description: ''
      operationId: healthcheck
      produces:
        - application/xml
        - application/json
      responses:
        '200':
          description: successful operation
        '405':
          description: Invalid input
  /project:
    get:
      tags:
        - projects
      summary: Fetches all resources
      description: ''
      operationId: getprojects
      produces:
        - application/xml
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/projects'
        '400':
          description: Invalid input
    post:
      tags:
        - projects
      summary: Adds a new resource.
      description: ''
      operationId: createprojects
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          description: Created projects object
          required: true
          schema:
            $ref: '#/definitions/projects'
      responses:
        '201':
          description: Created
        '400':
          description: Invalid input
  '/projects/{id}':
    get:
      tags:
        - 'projects/{id}'
      summary: Fetch resource by Id.
      description: ''
      operationId: 'getprojects/{id}'
      produces:
        - application/xml
        - application/json
      parameters:
        - name: id
          in: path
          description: 'The id that needs to be fetched. '
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/project'
        '405':
          description: Invalid input
    put:
      tags:
        - 'project/{id}'
      summary: Updates an existing resource.
      description: ''
      operationId: updateproject
      produces:
        - application/xml
        - application/json
      parameters:
        - name: id
          in: path
          description: id that need to be updated
          required: true
          type: string
        - in: body
          name: body
          description: Updated project object
          required: true
          schema:
            $ref: '#/definitions/project'
      responses:
        '200':
          description: Successfully updated data
        '400':
          description: Invalid input
    delete:
      tags:
        - 'project/{id}'
      summary: Deletes resource by Id.
      description: ''
      operationId: project
      produces:
        - application/xml
        - application/json
      parameters:
        - name: id
          in: path
          description: id that need to be deleted
          required: true
          type: string
      responses:
        '200':
          description: Successfully deleted data
        '400':
          description: Invalid input
definitions:
  Healthcheck:
    type: object
    properties:
      message:
        type: string
    xml:
      name: Healthcheck
  project:
    type: object
    properties:
      name:
        type: string
      summary:
        type: string
    xml:
      name: project
