on: 
  push:
    branches:
      - main
    # paths:
    #   - 'config/**'
    #   - 'site/**'
    #   - 'Dockerfile'
    #   - '.github/workflows/**'

jobs:

  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout master
      uses: actions/checkout@master

    - name: Update SHA
      run: echo $GITHUB_SHA > $GITHUB_WORKSPACE/helm/notes

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


    - name: Build and push.
      id: docker_build
      uses: docker/build-push-action@v2
      with:
          push: true
          tags: kasparov112000/files:latest,kasparov112000/files:${{ github.sha }}
          context: .
          file: ./Dockerfile
          build-args: |
            ENV_NAME=${{ secrets.ENV_NAME || 'LOCAL' }}
 
    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 3b23a2dd-3391-4d1a-a478-e2a5564de99c
    
    - name: Prep helm chart
      run: |
          mv ./helm/Chart.yaml ./helm/Chart.old.yaml &&
          cat ./helm/Chart.old.yaml | grep -v appVersion > ./helm/Chart.yaml &&
          echo -e "\r\nappVersion: v${GITHUB_REF##*/}\r\n" >> ./helm/Chart.yaml &&
          cat ./helm/Chart.yaml
    - name: Deploy
      run: |
        helm upgrade files ./helm/ \
          --install \
          --wait \
          --atomic \
          --timeout=10m \
          --set=app.name=files \
          --set=image.tag=${{ github.sha }} \
          --values=./helm/values.yaml